services:
  - type: web
    name: st-stitches-empire
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    runtime: python-3.12.10
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./tailor.db
