services:
  - type: web
    name: st-stitches-empire
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./tailor.db
